"""Generate validated nginx TLS/CIDR configuration; preview unless --apply is set."""

import argparse
import ipaddress
import re
import subprocess
from pathlib import Path


def render(domain, cidrs, cert, key, port):
    if not re.fullmatch(
        r"(?=.{1,253}$)[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?", domain
    ):
        raise ValueError("올바른 서버 도메인을 입력하세요.")
    if not cidrs:
        raise ValueError("허용할 사내망 또는 VPN CIDR이 필요합니다.")
    networks = [
        str(ipaddress.ip_network(value.strip(), strict=False)) for value in cidrs
    ]
    for path in (cert, key):
        if (
            not re.fullmatch(r"/[A-Za-z0-9_./-]+", str(path))
            or ".." in Path(path).parts
        ):
            raise ValueError("인증서 경로는 공백 없는 절대 경로여야 합니다.")
    if not 1 <= port <= 65535:
        raise ValueError("포트 범위를 확인하세요.")
    rules = "\n".join(f"    allow {network};" for network in networks)
    return f"""# Generated by ddeck configure_https.py
server {{
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name {domain};
    ssl_certificate {cert};
    ssl_certificate_key {key};
    ssl_protocols TLSv1.2 TLSv1.3;
{rules}
    deny all;
    client_max_body_size 26m;
    access_log off;
    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_read_timeout 120s;
    }}
}}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--domain")
    parser.add_argument("--cidr", action="append")
    parser.add_argument("--cert")
    parser.add_argument("--key")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--root", type=Path, default=Path("/opt/ddeck"))
    parser.add_argument("--apply", action="store_true")
    parser.add_argument(
        "--output", type=Path, default=Path("/etc/nginx/conf.d/ddeck.conf")
    )
    args = parser.parse_args()
    domain = args.domain or input("서버 도메인: ").strip()
    cidrs = args.cidr or input("허용 CIDR (쉼표 구분): ").split(",")
    cert = args.cert or input("인증서 fullchain 경로: ").strip()
    key = args.key or input("인증서 private key 경로: ").strip()
    content = render(domain, cidrs, cert, key, args.port)
    if not args.apply:
        print(content)
        return
    if not Path(cert).is_file() or not Path(key).is_file():
        parser.error("인증서와 키 파일을 먼저 준비하세요.")
    root = args.root.resolve()
    if not re.fullmatch(r"/[A-Za-z0-9_./-]+", str(root)):
        parser.error("서버 설치 경로에 공백이나 특수문자를 사용할 수 없습니다.")
    override = Path("/etc/systemd/system/ddeck.service.d/https.conf")
    config = {
        args.output: content,
        override: f"[Service]\nEnvironment=TRUSTED_PROXY_IPS=127.0.0.1/32\nExecStart=\nExecStart={root}/backend/.venv/bin/uvicorn app.main:app --no-access-log --no-proxy-headers --host 127.0.0.1 --port {args.port}\n",
    }
    previous = {path: path.read_bytes() if path.exists() else None for path in config}
    try:
        for path, text in config.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary = path.with_suffix(".tmp")
            temporary.write_text(text)
            temporary.replace(path)
        subprocess.run(["nginx", "-t"], check=True)
        subprocess.run(["systemctl", "daemon-reload"], check=True)
        subprocess.run(["systemctl", "restart", "ddeck"], check=True)
        subprocess.run(["systemctl", "reload", "nginx"], check=True)
    except Exception:
        for path, old in previous.items():
            if old is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(old)
        subprocess.run(["systemctl", "daemon-reload"], check=False)
        subprocess.run(["systemctl", "restart", "ddeck"], check=False)
        raise


if __name__ == "__main__":
    main()
