"""initial schema

Revision ID: 846cbbc04086
Revises: 
Create Date: 2026-09-20 07:16:40.043529+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.models.base

revision: str = '846cbbc04086'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('NOTICE', 'FREE', 'QNA', 'ARCHIVE', name='boardtype', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('read_role', sa.Enum('MEMBER', 'MANAGER', 'ADMIN', 'SUPERADMIN', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('write_role', sa.Enum('MEMBER', 'MANAGER', 'ADMIN', 'SUPERADMIN', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('allow_comment', sa.Boolean(), nullable=False),
    sa.Column('allow_attachment', sa.Boolean(), nullable=False),
    sa.Column('allow_secret', sa.Boolean(), nullable=False),
    sa.Column('notify_on_post', sa.Boolean(), nullable=False),
    sa.Column('page_size', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_boards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_boards_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_boards_id'), ['id'], unique=False)

    op.create_table('code_groups',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.Enum('SYSTEM', 'AUTH', 'SERVICE', 'INVENTORY', 'BOARD', 'CALENDAR', name='modulekey', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_groups_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_code_groups_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_groups_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_groups_module'), ['module'], unique=False)

    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('code_items',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['code_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'code', name='uq_code_item')
    )
    with op.batch_alter_table('code_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_items_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_items_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_items_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('MEMBER', 'MANAGER', 'ADMIN', 'SUPERADMIN', name='role', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', 'RESIGNED', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('signup_note', sa.Text(), nullable=True),
    sa.Column('last_login_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('attachments',
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'APPROVE', 'REJECT', 'SETTING_CHANGE', name='auditaction', native_enum=False, length=32), nullable=False),
    sa.Column('module', sa.Enum('SYSTEM', 'AUTH', 'SERVICE', 'INVENTORY', 'BOARD', 'CALENDAR', name='modulekey', native_enum=False, length=32), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_module'), ['module'], unique=False)

    op.create_table('calendars',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'DEPARTMENT', 'COMPANY', name='calendartype', native_enum=False, length=32), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendars_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendars_type'), ['type'], unique=False)

    op.create_table('customers',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('contact_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)

    op.create_table('devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('ANDROID', 'WINDOWS', 'LINUX', 'WEB', 'IOS', name='deviceplatform', native_enum=False, length=32), nullable=False),
    sa.Column('push_token', sa.String(length=512), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('locations',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('SITE', 'BUILDING', 'FLOOR', 'ROOM', 'RACK', 'VEHICLE', 'ETC', name='locationtype', native_enum=False, length=32), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_locations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_path'), ['path'], unique=False)

    op.create_table('module_settings',
    sa.Column('module', sa.Enum('SYSTEM', 'AUTH', 'SERVICE', 'INVENTORY', 'BOARD', 'CALENDAR', name='modulekey', native_enum=False, length=32), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'key', name='uq_module_setting')
    )
    with op.batch_alter_table('module_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_settings_module'), ['module'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('EVENT_REMINDER', 'EVENT_INVITED', 'EVENT_UPDATED', 'EVENT_CANCELED', 'SERVICE_ASSIGNED', 'BOARD_COMMENT', 'ACCOUNT_APPROVED', 'ACCOUNT_REJECTED', 'SYSTEM', name='notificationtype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('pushed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('posts',
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='poststatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_board_id'), ['board_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('assets',
    sa.Column('asset_no', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('serial_no', sa.String(length=150), nullable=True),
    sa.Column('barcode', sa.String(length=150), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'IN_USE', 'REPAIR', 'LOANED', 'DISPOSED', 'LOST', name='assetstatus', native_enum=False, length=32), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('holder_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('disposed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['holder_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_no'), ['asset_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_holder_id'), ['holder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_serial_no'), ['serial_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)

    op.create_table('post_comments',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_comments_post_id'), ['post_id'], unique=False)

    op.create_table('asset_movements',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.Enum('INBOUND', 'MOVE', 'ASSIGN', 'RETURN', 'REPAIR', 'DISPOSE', 'STOCKTAKE', name='movementtype', native_enum=False, length=32), nullable=False),
    sa.Column('from_location_id', sa.Uuid(), nullable=True),
    sa.Column('to_location_id', sa.Uuid(), nullable=True),
    sa.Column('from_holder_id', sa.Uuid(), nullable=True),
    sa.Column('to_holder_id', sa.Uuid(), nullable=True),
    sa.Column('from_status', sa.Enum('IN_STOCK', 'IN_USE', 'REPAIR', 'LOANED', 'DISPOSED', 'LOST', name='assetstatus', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('IN_STOCK', 'IN_USE', 'REPAIR', 'LOANED', 'DISPOSED', 'LOST', name='assetstatus', native_enum=False, length=32), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('moved_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('moved_by_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=60), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_holder_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['moved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_holder_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_movements_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_movements_moved_at'), ['moved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_movements_movement_type'), ['movement_type'], unique=False)

    op.create_table('service_tickets',
    sa.Column('ticket_no', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('site_address', sa.String(length=300), nullable=True),
    sa.Column('product_name', sa.String(length=150), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('serial_no', sa.String(length=120), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('symptom_id', sa.Uuid(), nullable=True),
    sa.Column('cause_id', sa.Uuid(), nullable=True),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_PARTS', 'COMPLETED', 'CANCELED', name='servicestatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='servicepriority', native_enum=False, length=32), nullable=False),
    sa.Column('channel', sa.Enum('PHONE', 'EMAIL', 'VISIT', 'WEB', 'INTERNAL', name='servicechannel', native_enum=False, length=32), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('received_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('due_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_warranty', sa.Boolean(), nullable=False),
    sa.Column('work_minutes', sa.Integer(), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('result_note', sa.Text(), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cause_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symptom_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_tickets_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_cause_id'), ['cause_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_is_warranty'), ['is_warranty'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_serial_no'), ['serial_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_symptom_id'), ['symptom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_ticket_no'), ['ticket_no'], unique=True)

    op.create_table('events',
    sa.Column('calendar_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('rrule', sa.String(length=250), nullable=True),
    sa.Column('recurrence_end', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELED', 'DONE', name='eventstatus', native_enum=False, length=32), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('service_ticket_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('service_logs',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('from_status', sa.Enum('RECEIVED', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_PARTS', 'COMPLETED', 'CANCELED', name='servicestatus', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('RECEIVED', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_PARTS', 'COMPLETED', 'CANCELED', name='servicestatus', native_enum=False, length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('work_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_logs_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('service_parts',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('part_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_parts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_parts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_parts_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('event_participants',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_organizer', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('response', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'TENTATIVE', name='participantresponse', native_enum=False, length=32), nullable=False),
    sa.Column('responded_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_participant')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_user_id'), ['user_id'], unique=False)

    op.create_table('event_reminders',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('INAPP', 'PUSH', 'EMAIL', name='remindermethod', native_enum=False, length=32), nullable=False),
    sa.Column('scheduled_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_reminders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_reminders_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_reminders_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_reminders_sent_at'), ['sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_reminders_sent_at'))
        batch_op.drop_index(batch_op.f('ix_event_reminders_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_event_reminders_id'))
        batch_op.drop_index(batch_op.f('ix_event_reminders_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_reminders_created_at'))

    op.drop_table('event_reminders')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_created_at'))

    op.drop_table('event_participants')
    with op.batch_alter_table('service_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_parts_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_service_parts_id'))
        batch_op.drop_index(batch_op.f('ix_service_parts_created_at'))

    op.drop_table('service_parts')
    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_logs_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_service_logs_id'))
        batch_op.drop_index(batch_op.f('ix_service_logs_created_at'))

    op.drop_table('service_logs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_ends_at'))
        batch_op.drop_index(batch_op.f('ix_events_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_events_category_id'))
        batch_op.drop_index(batch_op.f('ix_events_calendar_id'))

    op.drop_table('events')
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_tickets_ticket_no'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_symptom_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_serial_no'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_received_at'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_is_warranty'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_department_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_customer_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_completed_at'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_cause_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_category_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_assignee_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_action_id'))

    op.drop_table('service_tickets')
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_moved_at'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_id'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_asset_movements_asset_id'))

    op.drop_table('asset_movements')
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_comments_id'))
        batch_op.drop_index(batch_op.f('ix_post_comments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_post_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_post_comments_author_id'))

    op.drop_table('post_comments')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_serial_no'))
        batch_op.drop_index(batch_op.f('ix_assets_name'))
        batch_op.drop_index(batch_op.f('ix_assets_location_id'))
        batch_op.drop_index(batch_op.f('ix_assets_id'))
        batch_op.drop_index(batch_op.f('ix_assets_holder_id'))
        batch_op.drop_index(batch_op.f('ix_assets_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_category_id'))
        batch_op.drop_index(batch_op.f('ix_assets_barcode'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_no'))

    op.drop_table('assets')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_index(batch_op.f('ix_posts_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_posts_id'))
        batch_op.drop_index(batch_op.f('ix_posts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_posts_board_id'))
        batch_op.drop_index(batch_op.f('ix_posts_author_id'))

    op.drop_table('posts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('module_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_settings_module'))
        batch_op.drop_index(batch_op.f('ix_module_settings_id'))
        batch_op.drop_index(batch_op.f('ix_module_settings_created_at'))

    op.drop_table('module_settings')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_path'))
        batch_op.drop_index(batch_op.f('ix_locations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_locations_id'))
        batch_op.drop_index(batch_op.f('ix_locations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_locations_created_at'))
        batch_op.drop_index(batch_op.f('ix_locations_code'))

    op.drop_table('locations')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))
        batch_op.drop_index(batch_op.f('ix_devices_created_at'))

    op.drop_table('devices')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_customers_created_at'))

    op.drop_table('customers')
    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendars_type'))
        batch_op.drop_index(batch_op.f('ix_calendars_owner_id'))
        batch_op.drop_index(batch_op.f('ix_calendars_id'))
        batch_op.drop_index(batch_op.f('ix_calendars_department_id'))
        batch_op.drop_index(batch_op.f('ix_calendars_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_calendars_created_at'))

    op.drop_table('calendars')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_module'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_attachments_created_at'))

    op.drop_table('attachments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('code_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_items_id'))
        batch_op.drop_index(batch_op.f('ix_code_items_group_id'))
        batch_op.drop_index(batch_op.f('ix_code_items_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_code_items_created_at'))

    op.drop_table('code_items')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))
        batch_op.drop_index(batch_op.f('ix_departments_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_departments_created_at'))

    op.drop_table('departments')
    with op.batch_alter_table('code_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_groups_module'))
        batch_op.drop_index(batch_op.f('ix_code_groups_id'))
        batch_op.drop_index(batch_op.f('ix_code_groups_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_code_groups_created_at'))
        batch_op.drop_index(batch_op.f('ix_code_groups_code'))

    op.drop_table('code_groups')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_id'))
        batch_op.drop_index(batch_op.f('ix_boards_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_boards_created_at'))
        batch_op.drop_index(batch_op.f('ix_boards_code'))

    op.drop_table('boards')
    # ### end Alembic commands ###
