"""complete service inventory store worklog schema

Revision ID: 2cca8909675d
Revises: 846cbbc04086
Create Date: 2026-09-26 03:20:51.764074+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.models.base
revision: str = '2cca8909675d'
down_revision: str | None = '846cbbc04086'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worklog_drafts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('saved_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('worklog_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worklog_drafts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worklog_drafts_id'), ['id'], unique=False)

    op.create_table('worklogs',
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('author_name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('work_start', sa.String(length=5), nullable=False),
    sa.Column('work_end', sa.String(length=5), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('overtime', sa.Boolean(), nullable=False),
    sa.Column('overtime_note', sa.String(length=200), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('needs', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'TEAM', name='worklogvisibility', native_enum=False, length=32), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.create_index('ix_worklogs_author_date', ['author_id', 'work_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_worklogs_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worklogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worklogs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worklogs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worklogs_work_date'), ['work_date'], unique=False)

    op.create_table('stores',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('gripper_type', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_is_closed'), ['is_closed'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_name'), ['name'], unique=True)

    op.create_table('store_sets',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('set_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'set_no', name='uq_store_set_no')
    )
    with op.batch_alter_table('store_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_sets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_sets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_sets_store_id'), ['store_id'], unique=False)

    op.create_table('service_ticket_causes',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('symptom_id', sa.Uuid(), nullable=True),
    sa.Column('maker_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maker_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symptom_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'seq', name='uq_ticket_cause_seq')
    )
    with op.batch_alter_table('service_ticket_causes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_ticket_causes_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_causes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_causes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_causes_maker_id'), ['maker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_causes_symptom_id'), ['symptom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_causes_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('service_ticket_responders',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('responder_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['responder_id'], ['code_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'seq', name='uq_ticket_responder_seq')
    )
    with op.batch_alter_table('service_ticket_responders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_ticket_responders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_responders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_responders_responder_id'), ['responder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_ticket_responders_ticket_id'), ['ticket_id'], unique=False)

    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_store_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('to_store_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('from_status_item_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('to_status_item_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_asset_movements_to_store_id', 'stores', ['to_store_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_asset_movements_to_status_item_id', 'code_items', ['to_status_item_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_asset_movements_from_status_item_id', 'code_items', ['from_status_item_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_asset_movements_from_store_id', 'stores', ['from_store_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('set_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_item_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assets_status_item_id'), ['status_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_store_id'), ['store_id'], unique=False)
        batch_op.create_foreign_key('fk_assets_store_id', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_assets_status_item_id', 'code_items', ['status_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('store_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('fault_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('is_rental', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rental_type_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('rental_serials', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('rental_due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rental_returned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rental_return_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_tickets_fault_id'), ['fault_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_is_rental'), ['is_rental'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_legacy_no'), ['legacy_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_tickets_store_id'), ['store_id'], unique=False)
        batch_op.create_foreign_key('fk_service_tickets_store_id', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_service_tickets_rental_type_id', 'code_items', ['rental_type_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_service_tickets_fault_id', 'code_items', ['fault_id'], ['id'], ondelete='SET NULL')

    # Backfill old rows before imposing NOT NULL; do not leave server defaults
    # that differ from the ORM metadata.
    op.execute(sa.text("UPDATE assets SET set_no = 0 WHERE set_no IS NULL"))
    op.execute(sa.text("UPDATE service_tickets SET is_rental = false, rental_returned = false"))
    with op.batch_alter_table('assets') as batch_op:
        batch_op.alter_column('set_no', existing_type=sa.Integer(), nullable=False)
    with op.batch_alter_table('service_tickets') as batch_op:
        batch_op.alter_column('is_rental', existing_type=sa.Boolean(), nullable=False)
        batch_op.alter_column('rental_returned', existing_type=sa.Boolean(), nullable=False)



def downgrade() -> None:
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_tickets_fault_id', type_='foreignkey')
        batch_op.drop_constraint('fk_service_tickets_rental_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_service_tickets_store_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_service_tickets_store_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_legacy_no'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_is_rental'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_fault_id'))
        batch_op.drop_column('rental_return_date')
        batch_op.drop_column('rental_returned')
        batch_op.drop_column('rental_due_date')
        batch_op.drop_column('rental_serials')
        batch_op.drop_column('rental_type_id')
        batch_op.drop_column('is_rental')
        batch_op.drop_column('fault_id')
        batch_op.drop_column('store_id')
        batch_op.drop_column('legacy_no')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assets_status_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_assets_store_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_assets_store_id'))
        batch_op.drop_index(batch_op.f('ix_assets_status_item_id'))
        batch_op.drop_column('status_item_id')
        batch_op.drop_column('set_no')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_movements_from_store_id', type_='foreignkey')
        batch_op.drop_constraint('fk_asset_movements_from_status_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_asset_movements_to_status_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_asset_movements_to_store_id', type_='foreignkey')
        batch_op.drop_column('to_status_item_id')
        batch_op.drop_column('from_status_item_id')
        batch_op.drop_column('to_store_id')
        batch_op.drop_column('from_store_id')

    with op.batch_alter_table('service_ticket_responders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_ticket_responders_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_responders_responder_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_responders_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_responders_created_at'))

    op.drop_table('service_ticket_responders')
    with op.batch_alter_table('service_ticket_causes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_ticket_causes_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_causes_symptom_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_causes_maker_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_causes_id'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_causes_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_ticket_causes_category_id'))

    op.drop_table('service_ticket_causes')
    with op.batch_alter_table('store_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_sets_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_sets_id'))
        batch_op.drop_index(batch_op.f('ix_store_sets_created_at'))

    op.drop_table('store_sets')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_name'))
        batch_op.drop_index(batch_op.f('ix_stores_is_closed'))
        batch_op.drop_index(batch_op.f('ix_stores_id'))
        batch_op.drop_index(batch_op.f('ix_stores_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_stores_customer_id'))
        batch_op.drop_index(batch_op.f('ix_stores_created_at'))
        batch_op.drop_index(batch_op.f('ix_stores_brand_id'))

    op.drop_table('stores')
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worklogs_work_date'))
        batch_op.drop_index(batch_op.f('ix_worklogs_id'))
        batch_op.drop_index(batch_op.f('ix_worklogs_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_worklogs_created_at'))
        batch_op.drop_index(batch_op.f('ix_worklogs_author_id'))
        batch_op.drop_index('ix_worklogs_author_date')

    op.drop_table('worklogs')
    with op.batch_alter_table('worklog_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worklog_drafts_id'))
        batch_op.drop_index(batch_op.f('ix_worklog_drafts_created_at'))

    op.drop_table('worklog_drafts')
