"""operations outbox recurrence stock and active stores

Revision ID: ecdd8d8aea3c
Revises: 83c49d102fa1
Create Date: 2026-09-26 05:02:26.441175+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.models.base

revision: str = 'ecdd8d8aea3c'
down_revision: str | None = '83c49d102fa1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_at', app.models.base.UTCDateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_asset_movements_id'))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_id'))

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_id'))
        batch_op.add_column(sa.Column('photo_category', sa.String(32), nullable=True))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_at', app.models.base.UTCDateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_id'))

    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendars_id'))

    with op.batch_alter_table('code_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_groups_id'))

    with op.batch_alter_table('code_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_items_id'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_id'))

    with op.batch_alter_table('event_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_reminders_id'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_parent_id', sa.Uuid(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.create_index(batch_op.f('ix_events_recurrence_parent_id'), ['recurrence_parent_id'], unique=False)
        batch_op.create_foreign_key('fk_events_recurrence_parent', 'events', ['recurrence_parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    with op.batch_alter_table('module_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_settings_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_pending', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('push_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('push_after', app.models.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_id'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_id'))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_logs_id'))

    with op.batch_alter_table('service_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_deducted', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
        batch_op.drop_index(batch_op.f('ix_service_parts_id'))

    with op.batch_alter_table('service_ticket_causes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_ticket_causes_id'))

    with op.batch_alter_table('service_ticket_responders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_ticket_responders_id'))

    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_tickets_id'))

    with op.batch_alter_table('store_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_sets_id'))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
        batch_op.drop_index(batch_op.f('ix_stores_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    with op.batch_alter_table('worklog_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worklog_drafts_id'))

    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worklogs_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worklogs_id'), ['id'], unique=False)

    with op.batch_alter_table('worklog_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worklog_drafts_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_id'), ['id'], unique=False)
        batch_op.drop_column('is_active')

    with op.batch_alter_table('store_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_sets_id'), ['id'], unique=False)

    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_tickets_id'), ['id'], unique=False)

    with op.batch_alter_table('service_ticket_responders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_ticket_responders_id'), ['id'], unique=False)

    with op.batch_alter_table('service_ticket_causes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_ticket_causes_id'), ['id'], unique=False)

    with op.batch_alter_table('service_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_parts_id'), ['id'], unique=False)
        batch_op.drop_column('stock_deducted')

    with op.batch_alter_table('service_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_id'), ['id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.drop_column('push_after')
        batch_op.drop_column('push_attempts')
        batch_op.drop_column('push_pending')

    with op.batch_alter_table('module_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_settings_id'), ['id'], unique=False)

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_events_recurrence_parent', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_recurrence_parent_id'))
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.drop_column('recurrence_parent_id')

    with op.batch_alter_table('event_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_reminders_id'), ['id'], unique=False)

    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_id'), ['id'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    with op.batch_alter_table('code_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_items_id'), ['id'], unique=False)

    with op.batch_alter_table('code_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_groups_id'), ['id'], unique=False)

    with op.batch_alter_table('calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendars_id'), ['id'], unique=False)

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_id'), ['id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('hidden_at')
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)
        batch_op.drop_column('photo_category')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)

    with op.batch_alter_table('asset_movements', schema=None) as batch_op:
        batch_op.drop_column('hidden_at')
        batch_op.create_index(batch_op.f('ix_asset_movements_id'), ['id'], unique=False)

    # ### end Alembic commands ###
